files:
  include:
    - '_sass/**/*.s+(a|c)ss'
    - 'css/**/*.s+(a|c)ss'
  ignore:
    - 'css/jazzy.scss'
    - 'css/highlight.scss'
    - '_sass/3_level_generic/winstrap/**/*.s+(a|c)ss'
    - '_sass/3_level_generic/fontawesome/*.s+(a|c)ss'

rules:
  class-name-format:
    - 1
    - convention: hyphenatedbem
